/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_PantallaJuego;
import Controlador.Controlador_Hilos;

/**
 *
 * @author braghoick
 */
public class FRM_PantallaJuego extends javax.swing.JFrame {

    /**
     * Creates new form FRM_PantallaJuego
     */
    
    Controlador_Hilos controlador_Hilos;
    Controlador_FRM_PantallaJuego controlador_FRM_PantallaJuego;
    
    public String posicionPersonaje="Piso";
    
    public FRM_PantallaJuego() {
        initComponents();
        
        setSize(1280, 740);
        
        controlador_Hilos=new Controlador_Hilos(this);
        controlador_FRM_PantallaJuego= new Controlador_FRM_PantallaJuego(this);
        this.addKeyListener(controlador_FRM_PantallaJuego);
        
        controlador_Hilos.start();
        
        
    }
    
    public void moverFondo(){
    
        if(JL_Fondo.getX()>-8960){
        
            JL_Fondo.setLocation(JL_Fondo.getX()-5, JL_Fondo.getY());
        }
        
        else{
        
            JL_Fondo.setLocation(0, JL_Fondo.getY());
        }
    }
    
    public void verificarEstado(){
    
        if(posicionPersonaje.equals("Aire")){
        
            JL_Personaje.setLocation(JL_Personaje.getX(), JL_Personaje.getY()-20);
        }
        
        if(JL_Personaje.getY()<=300){
        
            posicionPersonaje="Caida";
        }
        
        if(posicionPersonaje.equals("Caida")){
            
            JL_Personaje.setLocation(JL_Personaje.getX(), JL_Personaje.getY()+30 );
        }
        
        if(JL_Personaje.getY()>=450){
        
            posicionPersonaje="Piso";
        }
        
        if(posicionPersonaje.equals("Piso")){
        
            JL_Personaje.setLocation(JL_Personaje.getX(), 450);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_Enemigo = new javax.swing.JLabel();
        JL_Personaje = new javax.swing.JLabel();
        JL_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_Enemigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/MrHungry2.gif"))); // NOI18N
        getContentPane().add(JL_Enemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 182, -1, -1));

        JL_Personaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Avo2.gif"))); // NOI18N
        getContentPane().add(JL_Personaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 450, -1, -1));

        JL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Prueba fondo.jpg"))); // NOI18N
        getContentPane().add(JL_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10240, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_PantallaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_Enemigo;
    private javax.swing.JLabel JL_Fondo;
    private javax.swing.JLabel JL_Personaje;
    // End of variables declaration//GEN-END:variables
}
